src/StreamBet/Models/ApplicationDbContext.cs
using System;
using Microsoft.Data.Entity;
using Microsoft.Data.Entity.Metadata;

namespace StreamBet.Models
{
    public class ApplicationDbContext : DbContext
    {
        private static bool _created;

        public ApplicationDbContext()
        {
            // Create the database and schema if it doesn't exist
            if (!_created)
            {
                Database.AsRelational().ApplyMigrations();
                _created = true;
            }
        }

        public DbSet<Streamer> Streamers { get; set; }

        protected override void OnModelCreating(ModelBuilder builder)
        {
            builder.Entity<Streamer>().Ignore(m => m.IsLive);
            base.OnModelCreating(builder);
            // Customize the ASP.NET Identity model and override the defaults if needed.
            // For example, you can rename the ASP.NET Identity table names and more.
            // Add your customizations after calling base.OnModelCreating(builder);
        }
    }
}

src/StreamBet/Models/IStreamerRepo.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Threading.Tasks;
using StreamBet.ViewModels;

namespace StreamBet.Models
{
    public interface IStreamerRepo
    {
        Task<IAsyncEnumerable<Streamer>> GetStreamers();

        Task<Streamer> GetStreamerAsync(int id);

        Task AddStreamerAsync(Streamer s);

        Task EditStreamerAsync(int id, EditViewModel model);

        Task<bool> DeleteStreamerAsync(int id);
    }
}

src/StreamBet/Models/Streamer.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations.Schema;
using TwitchAPI.Models;

namespace StreamBet.Models
{
    public class Streamer
    {
        /// <summary>
        /// Unique Identifier for streamer
        /// </summary>
        public int Id { get; set; }

        /// <summary>
        /// Streamer name
        /// </summary>
        public string Name { get; set; }

        /// <summary>
        /// Link to streamer's stream
        /// </summary>
        public string StreamLink { get; set; }

        /// <summary>
        /// Live status of streamer
        /// </summary>
        [NotMapped]
        public bool IsLive { get; set; }

        public async Task<bool> getLiveStatus()
        {
            Stream s = new Stream();
            await s.getStream(this.Name);

            if (s.SStream != null)
            {
                return true;
            }
            else
            {
                return false;
            }
        }
    }

    public class StreamerStatusModel
    {
        /// <summary>
        /// 
        /// </summary>
        public int Id { get; set; }

        /// <summary>
        /// 
        /// </summary>
        public string Description { get; set; }
    
    }

}

src/StreamBet/Models/StreamerRepo.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using StreamBet.ViewModels;
using TwitchAPI.Models;

namespace StreamBet.Models
{
    public class StreamerRepo : IStreamerRepo
    {
        private readonly ApplicationDbContext _db;

        public StreamerRepo(ApplicationDbContext db)
        {
            _db = db;
        }

        public async Task AddStreamerAsync(Streamer s)
        {
            _db.Streamers.Add(s);
            await _db.SaveChangesAsync();
        }

        public async Task EditStreamerAsync(int id, EditViewModel model)
        {
            var streamer = await this.GetStreamerAsync(id);
            streamer.Name = model.Name;
            streamer.StreamLink = model.StreamLink;
            await _db.SaveChangesAsync();
        }

        public async Task<bool> DeleteStreamerAsync(int id)
        {
            var streamer = await _db.Streamers.SingleOrDefaultAsync(s => s.Id == id);
            if (streamer != null)
            {
                _db.Streamers.Remove(streamer);
                await _db.SaveChangesAsync();
                return true;
            }
            else
            {
                return false;
            }
        }

        public async Task<Streamer> GetStreamerAsync(int id)
        {
            Streamer st =  await _db.Streamers.SingleOrDefaultAsync(s => s.Id == id);

            Stream ss = new Stream();
            await ss.getStream(st.Name);

            if (ss.SStream != null)
            {
                st.IsLive = true;
            }
            else
            {
                st.IsLive = false;
            }

            return st;
        }
        
        public async Task<IAsyncEnumerable<Streamer>> GetStreamers()
        {

            await _db.Streamers.ForEachAsync(async st => st.IsLive = await st.getLiveStatus());
            
            return _db.Streamers.AsAsyncEnumerable();
        } 
    }
}

src/StreamBet/ViewModels/StreamerViewModels.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNet.Mvc.Rendering;

namespace StreamBet.ViewModels
{
    public class EditViewModel
    {
        [Required]
        [Display(Name ="Name")]
        public string Name { get; set; }

        [Required]
        [DataType(DataType.Url)]
        [Display(Name = "Link to stream")]
        public string StreamLink { get; set; }
    }

    public class NewViewModel
    {
        [Required]
        [Display(Name ="Name")]
        public string Name { get; set; }

        [Required]
        [DataType(DataType.Url)]
        [Display(Name = "Link to stream")]
        public string StreamLink { get; set; }
    }
}

src/StreamBet/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNet.Mvc;

namespace StreamBet.Controllers
{
    [Route("")]
    public class HomeController : Controller
    {
        [HttpGet("")]
        public IActionResult Index()
        {
            return View();
        }
    }
}

src/StreamBet/Controllers/StreamerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNet.Mvc;
using StreamBet.Models;
using StreamBet.ViewModels;

namespace StreamBet.Controllers
{
    [Route("[controller]")]
    public class StreamerController : Controller
    {
        private IStreamerRepo Repository { get; }

        public StreamerController(IStreamerRepo repository)
        {
            this.Repository = repository;
        }

        [HttpGet("")]
        public IActionResult Index()
        {
            return View(this.Repository.GetStreamers());
        }

        [HttpGet("New")]
        public IActionResult New()
        {
            return View();
        }

        [HttpPost("New")]
        public async Task<IActionResult> New(NewViewModel model)
        {
            if (ModelState.IsValid)
            {
                var streamer = new Streamer { Name = model.Name, StreamLink = model.StreamLink };
                await this.Repository.AddStreamerAsync(streamer);
                return RedirectToAction("Index");
            }

            // If we got this far, something failed. redisplay form
            return View(model);
        }

        [HttpGet("{id}/Edit")]
        public async Task<IActionResult> Edit(int id)
        {
            var streamer = await this.Repository.GetStreamerAsync(id);
            return View(new EditViewModel { Name = streamer.Name, StreamLink = streamer.StreamLink });
        }

        [HttpPost("{id}/Edit")]
        public async Task<IActionResult> Edit(int id, EditViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            await this.Repository.EditStreamerAsync(id, model);
            return RedirectToAction("Index");
        }

        [HttpPost("{id}/Delete")]
        public async Task<IActionResult> Delete(int id)
        {
            await this.Repository.DeleteStreamerAsync(id);
            return RedirectToAction("Index");
        }
    }
}

src/StreamBet/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>Stream Bet</h1>
    <p>Welcome to StreamBet!</p>

</div>

src/StreamBet/Views/Shared/_Layout.cshtml
@inject IOptions<AppSettings> AppSettings
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewBag.Title - @AppSettings.Options.SiteTitle</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/css/bootstrap.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="//ajax.aspnetcdn.com/ajax/bootstrap/3.3.4/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/css/bootstrap.min.css"
              asp-fallback-test-class="hidden" asp-fallback-test-property="visibility" asp-fallback-test-value="hidden" />
    </environment>
</head>
<body>
    <div class="navbar navbar-inverse">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-controller="Home" asp-action="Index" class="navbar-brand">@AppSettings.Options.SiteTitle</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-controller="Streamer" asp-action="Index">Streamers</a></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2015 - @AppSettings.Options.SiteTitle</p>
        </footer>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/jquery.js"></script>
        <script src="~/lib/bootstrap/js/bootstrap.js"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="//ajax.aspnetcdn.com/ajax/jquery/jquery-2.1.4.min.js"
                asp-fallback-src="~/lib/jquery/jquery.min.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="//ajax.aspnetcdn.com/ajax/bootstrap/3.3.4/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery">
        </script>
    </environment>
    <script src="~/lib/jquery-ujs/rails.js"></script>
    <script src="~/js/app.js"></script>

    @RenderSection("scripts", required: false)
</body>
</html>

src/StreamBet/Views/Streamer/Edit.cshtml
@model EditViewModel
@{
    ViewBag.Title = "Edit Streamer";
}

<h2>@ViewBag.Title</h2>

<form asp-controller="Streamer" asp-action="Edit" method="post" class="form-horizontal" role="form">
    <h4>Edit streamer.</h4>
    <hr />
    <div asp-validation-summary="ValidationSummary.All" class="text-danger"></div>
    <div class="form-group">
        <label asp-for="Name" class="col-md-2 control-label"></label>
        <div class="col-md-10">
            <input asp-for="Name" class="form-control" />
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group">
        <label asp-for="StreamLink" class="col-md-2 control-label"></label>
        <div class="col-md-10">
            <input asp-for="StreamLink" class="form-control" />
            <span asp-validation-for="StreamLink" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" class="btn btn-default" value="Edit" />
        </div>        
    </div>
</form>

@section Scripts {
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
}

src/StreamBet/Views/Streamer/Index.cshtml
@model IEnumerable<Streamer>
@{
    ViewBag.Title = "Streamers";
}

<h2>@ViewBag.Title</h2>
<table class="table table-striped">
    <tr>
        <td>Live</td>
        <th>Id</th>
        <th>Name</th>
        <th>Stream Link</th>
        <th>Actions</th>
    </tr>
    @foreach(var streamer in this.Model)
    {
        <tr>
            <td>
            @if (streamer.IsLive)
            {
                <p>LIVE!</p>
            }
            else
            {
                <p>OFFLINE!</p>
            }</td>
            <td>@streamer.Id</td>
            <td>@streamer.Name</td>
            <td><a href="@streamer.StreamLink">@streamer.StreamLink</a></td>
            <td>
                <a asp-action="Edit" asp-route-id="@streamer.Id">Edit</a>
                <a asp-action="Delete" asp-route-id="@streamer.Id" data-method="post" data-confirm="Are you sure?">Delete</a>
            </td>
        </tr>
    }
</table>
<p><a class="btn btn-primary" role="button" asp-action="New">New streamer</a></p>

src/StreamBet/Views/Streamer/New.cshtml
@model NewViewModel
@{
    ViewBag.Title = "New Streamer";
}

<h2>@ViewBag.Title</h2>

<form asp-controller="Streamer" asp-action="New" method="post" class="form-horizontal" role="form">
    <h4>Create a new streamer.</h4>
    <hr />
    <div asp-validation-summary="ValidationSummary.All" class="text-danger"></div>
    <div class="form-group">
        <label asp-for="Name" class="col-md-2 control-label"></label>
        <div class="col-md-10">
            <input asp-for="Name" class="form-control" />
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group">
        <label asp-for="StreamLink" class="col-md-2 control-label"></label>
        <div class="col-md-10">
            <input asp-for="StreamLink" class="form-control" />
            <span asp-validation-for="StreamLink" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" class="btn btn-default" value="Create" />
        </div>        
    </div>
</form>

@section Scripts {
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
}

src/StreamBet/Views/_GlobalImport.cshtml
@using StreamBet
@using StreamBet.Models
@using StreamBet.ViewModels
@using Microsoft.Framework.OptionsModel
@addTagHelper "*, Microsoft.AspNet.Mvc.TagHelpers"